language: python

matrix:
    fast_finish: true
    include:
    - python: 2.7
    - python: 3.6
    - python: 3.7
      sudo: required
      dist: xenial
    - python: 3.8-dev
      sudo: required
      dist: xenial
    allow_failures:
    - python: 3.8-dev

cache: pip

install:
  - pip install -r requirements_dev.txt

script:
  - pytest --sw -vv tests/test.py tests/
