#!/bin/bash -v
# python setup.py sdist --formats=gztar upload
# python setup.py bdist_egg upload
#python setup.py register sdist --formats=gztar bdist_egg upload
#
# for info, see:
#    https://packaging.python.org/tutorials/distributing-packages/#packaging-and-distributing-projects
twine upload dist/generateDS-2.28rc0-py2.7.egg dist/generateDS-2.28rc0.tar.gz
